netz98/n98-magerun

src/N98/Magento/Command/System/Cron/RunCommand.php
sprintf was missing, so the two parameters for sprintf where given to the constructor of the Exception class instead resulting in the following error:
Fatal error: Wrong parameters for Exception([string $exception [, long $code [, Exception $previous = NULL]]]) in phar:///usr/local/bin/n98-magerun.phar/src/N98/Magento/Command/System/Cron/RunCommand.php on line 68
=> Fixed missing sprintf when creating Exception in sys:cron:run command

config.yaml, readme.rst, src/N98/Magento/Command/Database/DumpCommand.php
The @importexporttemp group is added to the @stripped group such that it not only removes the temp tables for the Dataflow module, but also for ImportExport.
The @iimportexporttemp group only contains one table (importexport_importdata, which can contain both product and customer data), but has been added such that it is analogous to the handling of the dataflow temp tables.
=> [TASK] Add importexporttemp table group for db:dump command

config.yaml, readme.rst
The index_event and index_process_event tables are needed to record the status
of dependent indexers (currently only the cataloginventory index), but are never
cleared. Excluding these tables from a database dump can significantly reduce
the size of the dump.
=> [TASK] Add index event tables to @ids table group of the db:dump command

src/N98/Magento/Command/System/Cron/AbstractCronCommand.php, src/N98/Magento/Command/System/Cron/RunCommand.php
When sys:cron:run is called without any arguments, a dialog is presented to the user where he can choose a job by entering a number.
It was however also possible to execute a job by entering invalid input:
- if 0 is entered, the last job in the list was executed
- if a negative number was entered, the first job in the list was executed
- if non-numeric value was entered, the last job in the list was executed
This commit fixes the above issues by showing an error if incorrect input is supplied.
=> [BUGFIX] Improve sys:cron:run input handling

src/N98/Magento/Command/System/Setup/CompareVersionsCommand.php
Updates the ordering of `sys:setup:compare-versions` so that it is output in alphabetical order.
Checked with the unit tests, and here's a sample of my run locally.
```
/lukerodgers.co.uk/checkouts/n98-magerun/bin/n98-magerun sys:setup:compare-versions
+-------------------------------+------------+------------+------------+--------+
| Setup                         | Module     | DB         | Data       | Status |
+-------------------------------+------------+------------+------------+--------+
| admin_setup                   | 1.6.1.1    | 1.6.1.1    | 1.6.1.1    | OK     |
| adminnotification_setup       | 1.6.0.0    | 1.6.0.0    | 1.6.0.0    | OK     |
| api2_setup                    | 1.0.0.0    | 1.0.0.0    | 1.0.0.0    | OK     |
| api_setup                     | 1.6.0.1    | 1.6.0.1 …
```
=> Update ordering of compare-versions so that output is alphabetised

src/N98/Magento/Command/Database/InfoCommand.php, src/N98/Util/Console/Helper/DatabaseHelper.php
Hi
I was testing Magento with a db connection using sockets and noticed a couple of PHP notices like this:
`Notice: Undefined index: host`
This pull request fixes this.
While fixing this, I noticed the output of the connection strings of the `db:info` command was incorrect when using sockets, this is fixed. I also noticed the connection strings didn't contain the port when not using sockets, so this is fixed too now.
I also removed some code from `DatabaseHelper::getConnection` which was already called in `DatabaseHelper::detectDbSettings` so that wasn't necessary anymore.
I do have some extra remarks about this pull request:
- I have no experience with the JDBC connection string, so the changes are based on info I found on the web
- I hardcoded port 3306, as I see it is also hardcoded in …
=> Some small database connection & db:info improvements

src/N98/Magento/Command/Admin/User/CreateUserCommand.php
Use askHiddenResponse to hide the password by default. To maintain
backwards compatability false isn't passed as the final argument. This
means if the terminal doesn't support hidden input plain text will be
used rather than erroring. Closes #60.
=> Hide password when creating admin account.

src/N98/Magento/Application.php
The --skip-root-check and --skip-config options were both defined as
InputOption::VALUE_OPTIONAL. In this situation the option will be
assigned the value of an argument that is directly following it. In the
case of a command this is the command name itself, but this causes every
argument to shift along. Since these options are boolean switches, they
can be changed to InputOption::VALUE_NONE. Closes #521.
=> Fix global options swallowing arguments.

config.yaml, src/N98/Magento/Command/Developer/Theme/InfoCommand.php
Hi @tkn98
OK, I am creating new PR, as you asked, this time against `develop` branch.
I can see now, there is 1 commit and 2 files changed, instead of 22 commits to merge :)
I have also changed my repo username, so it will fit now to github account.
Previous PR was: #531 and #534
I am pasting my original message to you guys:
First of all, great work guys with magerun, I can't imagine to work with Magento without Magerun :)
I have proposition of new command to Magerun pack.
I have added command to magerun, which shows current design settings on particular store view.
When developer works on Magento with one store view, he/she simply goes to configuration to obtain design settings.
If store has more than one store view, it is annoying to obtain design settings on all store views.
Command …
=> Added display current design settings on particular store

tests/N98/Magento/Command/Developer/Module/Rewrite/ConflictsCommandTest.php
Inspired by discussion in issue #523, this adds an option `--mock-conflict` to mock a positive conflict detection while testing:
```
$ magerun dev:module:rewrite:conflict --mock-conflict
┌────────┬──────────────────────────────┬────────────────────────────────────────────────────────────┬────────────────────────────────────────────────────────────┐
│blocks  │n98/mock                      │Mage_Customer_Block_Account, Mage_Tag_Block_All             │Mage_N98_Block_Mock                                         │
└────────┴──────────────────────────────┴────────────────────────────────────────────────────────────┴────────────────────────────────────────────────────────────┘
1 conflict was found!
```
I used `Mage_Customer_Block_Account` and `Mage_Tag_Block_All` as the guinea pigs since I …
=> Creating a test for rewrite conflict command where a conflict is found

src/N98/Magento/Command/Developer/Module/Observer/ListCommand.php
If the class node isn't set in the configuration for an observer,
Magento will also check for the model node. Added support for this to
the list command.
=> Improve observer list accuracy.

src/N98/Magento/Application.php
I think it would make sense to re-initialize the magento root folder in the `reinit` method. This is prevented by the flag `$_magentoDetected`.
This behaviour caused some errors in the "install" command, which changes into the root folder, calls the `reinit` method, and runs two more commands.
To reproduce the problem:
* extract sources to a subfolder "public"
* from the "public"'s parent, run n98-magerun (with --noDownload option, and --installationFolder=public)
What happens:
* The installation itself succeeds, the detected root folder is "public" (relative path)
* ` \chdir($this->config['installationFolder']);` is called
* `$this->getApplication()->reinit();` is called, but the `_magentoRootFolder` is not updated
* The reindexAll command is run. During …
=> reset magento root folder in `N98\Magento\Application::reinit`

config.yaml
The Magento wishlist tables include a foreign key to the customer data tables. If those customer data tables are not included, the wishlist data is basically useless.
This PR excludes the wishlist tables from the database dump when the `@customers` table group is used in the `--strip` option.
=> Excluding wishlist tables

src/N98/Magento/Command/System/Check/Settings/CookieDomainCheckAbstract.php, src/N98/Magento/Command/System/Check/Settings/SecureCookieDomainCheck.php, src/N98/Magento/Command/System/Check/Settings/UnsecureCookieDomainCheck.php
For both secure and unsecure base URLs.
This commit intends to fix #584
- Removed code-duplication.
- Obtained actual base-URL value.
- Wrote a rough cookie domain validation method.
=> Fix Cookie Domain validation

config.yaml, src/N98/Magento/Command/Installer/InstallCommand.php
Downloads were not verified against a checksum. This has been fixed by introducing a checksum for each package.
- SHA checksums for download packages.
- exit with error when download fails (e.g. due to failed checksum validation).
I generated the checksums on my box with shasum. In case there is a mismatch, please peer review them. Download URLs from the config.yaml file, downloaded with wget.
=> Checksum for package downloads

.travis.yml, src/N98/Magento/Command/System/Check/Settings/CookieDomainCheckAbstract.php, tests/N98/Magento/Command/System/Check/Settings/CookieDomainCheckAbstractTest.php, tests/N98/Util/AutoloadRestorerTest.php
Put the cookie-domain-check under unit-testing and found some flaws by
that.
Fixed the cookie domain check for the most common configuration for stable
use.
This still does not check against all nuances which could bite oneself
but coverage is much higher now. Also it's easier to test in case of a
regression.
Additionally the error message wording has been improved.
=> Fixed Cookie Domain Check

src/N98/Magento/Command/AbstractMagentoCommand.php
An operation on a string variable caused a fatal error because of using an array operator on string (array push operator).
This has been fixed by using the string concatenation operator.
Fixes #632
=> Fix fatal error on string operation

src/N98/Magento/Command/AbstractMagentoCommand.php, src/N98/Magento/Command/Cache/AbstractCacheCommand.php, src/N98/Magento/Command/Cache/CleanCommand.php
```
n98-magerun.phar cache:disable eavv
Cache eavv disabled
```
```
n98-magerun.phar cache:disable eavv
[InvalidArgumentException]  
Invalid cache type: eavv    
cache:disable [code]
```
Same for `cache:enable` and `cache:clean`.
Solves issue #620
=> Validate cache codes on cache enable, disable and clean.

src/N98/Magento/Command/Database/DumpCommand.php
The table group help is autogenerated.
Additionally it was in the static help block.
The documentation was fixed.
=> Fix: Dump command was showing duplicate help

changes.txt, src/N98/Magento/Command/Customer/AbstractCustomerCommand.php, src/N98/Magento/Command/Customer/DeleteCommand.php
In b5c7137 the customer:delete command was introducted. It made use of an
Dialog helper that had the getQuestion() method.
The current Dialog helper does not have such a method any longer. Now the
Dialog helper is:
Symfony\Component\Console\Helper\DialogHelper
which is deprecated.
Fix is to not call that method any longer. Instead a private helper
method is called which returns the string of the question.
Closes #643
=> [BUGFIX] #643 fatal error in customer:delete

src/N98/Magento/Command/Developer/Module/Rewrite/AbstractRewriteCommand.php
We sometimes see this PHP warning in our system.log files of Magento:
```
Warning: Invalid argument supplied for foreach()  in n98-magerun.phar/src/N98/Magento/Command/Developer/Module/Rewrite/ListCommand.php on line 41
```
This PR fixes this.
The problem is that the `$return` array is initialized with values, instead of keys. The resulting array then looks something like this:
```php
array(7) {
[0] =>
string(6) "blocks"
[1] =>
string(6) "models"
[2] =>
string(7) "helpers"
'models' =>
array(36) {
'compiler/process' =>
array(1) {
[0] =>
string(40) "Aitoc_Aitsys_Model_Core_Compiler_Process"
}
'catalog_resource_eav_mysql4/category_tree' =>
array(1) {
[0] =>
string(76) "Aitoc_Aitpermissions_Model_Rewrite_CatalogModelResourceEavMysql4CategoryTree"
}
...
```
You can see the first 3 values are …
=> Fix for PHP warning in Rewrite command

src/N98/Magento/Command/LocalConfig/GenerateCommand.php
Looks like a regression was introduced in [ca97317f3076abb9ff06a6e582bed1aef4489caf](https://github.com/netz98/n98-magerun/commit/ca97317f3076abb9ff06a6e582bed1aef4489caf#diff-19deddad71767595667346435c7729e7R127) where `db-name` was replaced with `db-pass`. This results in the database name never being prompted for causing the command to error and exit.
I also added a space to the prompt prefix
=> Fix database name prompt + Add space to message prefix

src/N98/Magento/Command/LocalConfig/GenerateCommand.php, tests/N98/Magento/Command/LocalConfig/GenerateCommandTest.php
As promised in #657 
* Add method to base TestCase class to get the Magento Root dir during testing
* Add tests to cover all permutations of input
* Fix bug when required argument was missing, config was still generated - now throws an exception
=> Unit tests for LocalConfigGenerate

phpunit.xml.dist, src/N98/Magento/Command/PHPUnit/TestCase.php, tests/N98/Magento/Command/Installer/UninstallCommandTest.php
Currently with PHPUnit (AFAIK) there is no way to set a default test suite to run. So if a develop runs `vendor/bin/phpunit` ALL test suites will be run, and the Magento test environment will be removed. This is annoying as you cannot run the tests suite more than once. We have some options:
* Create a script to run tests like `runtests.php` which will just run the default test suite. (My preference)
* Update the documentation and inform to use `--testsuite` when running the tests. (I think this is a pretty annoying burden)
I'm opening this to see how it runs on travis. It *SHOULD* run the suite `n98-magerun-tests` first and then the suite `n98-magerun-magento-uninstall-tests`. I was going to separate the calls to the testsuites but I think this will affect the coverage, as the second …
=> WIP - Separate test suite for Uninstall command

changes.txt, src/N98/Magento/Command/LocalConfig/GenerateCommand.php, tests/N98/Magento/Command/LocalConfig/GenerateCommandTest.php
the GenerateCommand has problems properly wrapping a string into a CDATA section when it comes to strings containing the word "CDATA" or "]]>".
=> [FIX] add wrapCdata test

src/N98/Magento/Command/System/MaintenanceCommand.php
Commands which enable and disable system maintenance check if
touch/unlink commands returned success instead of doing that blindly.
=> Add error checking on sys:maintenance calls

composer.json, composer.lock
Currently the composer.json is causing dependency hell because you're relying on specific feature versions libs instead of "at least this version, up to the next release that breaks backwards compatibility".
Symfony 2.3 components are still in LTS, and are more suitable to depend upon. Currently we can't rely on 2.3 because `n98-mageun` relies on specifically `2.6.*`, so this is an issue when installing `n98-magerun` into a project that also relies on anything other than 2.6 Symfony components.
I've also updated some other libs, and removed the `"minimum-stability": "dev"` option as you're specifying `@dev` in the composer lib dependency, which is the only one I can see is necessary to use bleeding edge (although this should be using the alpha releases).
TODO:
=> Updating symfony dependencies to ~2.3 in composer.json

autocompletion/bash/bash_complete
Proposed fix for #695 Bash autocomplete doesn't allow path completion
Also make a single call to complete for all 3 names instead of 3 separate calls
=> Bash autocomplete: Allow path completion

src/N98/Magento/Command/Cache/CleanCommand.php
Uses getTypes from cache instance to include custom cache types as well.
By default magerun uses Mag::app->useCache() in order to retrieve the cache types to clean, but this only seems to get the core cache types. Custom cache types added by user extensions are ignored. This fixes the issue.
=> Include custom cache-types when cleaning cache

src/N98/Magento/Command/Database/ConsoleCommand.php, src/N98/Util/Console/Helper/DatabaseHelper.php
I'm creating a new pull request based on the develop branch.
This is for a small change to the db:console command to accept the --mycli or -m switches. If mycli (http://mycli.net/) is installed as a binary available in your path, it will be used instead of the mysql command to connect to the MySQL server when one of the above switches is set.
Using mycli is very convenient for Magento with its auto-completion features on commands and table names.
It makes more sense to provide an optional switch (--mycli or -m) in n98-magerun instead of creating a custom shell alias since the impact of doing the switch is much less than changing the MySQL client via an alias. The alias may have unintentional consequences with other applications that depend on the `mysql` command to be the actual `mysql` …
=> Enable mycli client for MySQL via db:console

build.sh, build/tasks/PatchedPharPackageTask.php
Compressing a phar file needs a lot of open file descriptors/file handles, roughly as many as compressed files it contains.
As that limit is (for magerun normally) below the hard limit (of an assumed 4096), *build.sh* raises the soft-limit to the hard-limit prior running the phing build.
- The *build.sh* script raises the openfiles soft-limit to the maximum
possible size (the hard-limit).
- The *build.sh* script did not exit with a non-zero exit status when it
ran into an error on build. Fix by keeping the exit status and returning
it.
- The patched phing task to create the phar file shows the number of files
that are compressed.
- The patched phing task catches BadMethodCallException on
Phar::compressFiles(), checks for the exception message and inserts a
more-saying exception message in …
=> [FIX] phar compression openfiles limit

.travis.yml, src/N98/Util/String.php
changes in 2c4a331 are not backwards compatible so would break on minor
release.
this commit adds the String utility class again ensuring that potential
magerun extensions do not break.
=> [TASK] #691 PHP 7 backward compat

config.yaml
=> [TASK] Added some magento-mirror versions and changed LokeyCoding to OpenMage

src/N98/Magento/Command/System/Cron/AbstractCronCommand.php
This pull request addresses issue #727 where cron expressions in the `core_config_data` table were not being displayed when running `sys:cron:list`.
In accordance with the [Magento core cron model](https://github.com/OpenMage/magento-mirror/blob/magento-1.9/app/code/core/Mage/Cron/Model/Observer.php#L86-L98), we should load both and merge them together.
Matching core functionality, the database entries take priority over XML entries.
=> [#727] Merge DB cron expressions from the database into the XML

src/N98/Magento/Command/Developer/Module/Rewrite/ConflictsCommand.php, tests/N98/Magento/Command/Developer/Module/Rewrite/ConflictsCommandTest.php
This makes the `dev:module:rewrite:conflicts` command return a non-zero exit code if a rewrite conflict is detected.  This is useful for integration testing, so that a build will be marked as failed when a conflict is introduced.
=> Return non-zero status when module rewrite conflict is positive

src/N98/Magento/Command/Installer/InstallCommand.php, src/N98/Util/OperatingSystem.php, tests/N98/Util/OperatingSystemTest.php
Use PHP_BINARY constant if available to run the magento install command using the same PHP binary as magerun.
Also fix minor issue for running phpunit on osx/darwin
=> [FIX] install cmd fails using custom php binary

src/N98/Magento/Command/Developer/Module/ListCommand.php
if a module definition property (version,codepool) contains a whitespace character the output table display will be broken and the filters wont apply correctly.
By removing whitespace when collecting the module properties the output table will render correctly (even with a whitespace character defined in the modules definition file) and filters will still correctly apply.
=> Sanitize module properties

src/N98/Magento/Command/Database/DumpCommand.php
Prepend LANG=C LC_CTYPE=C LC_ALL=C to sed command
issue: #771
=> [FIX] sed: RE error: illegal byte sequence on myqldump

src/N98/Magento/Command/Database/DumpCommand.php
The intention of this is to make it easier to grok when looking at both generated commands.
With this modification it will generate commands like:
```
mysqldump --single-transaction --quick --routines --no-data -h'127.0.0.1'
mysqldump --single-transaction --quick --routines -h'127.0.0.1' --ignored-tables-go-here -ad-infinitum
```
When you have hundreds of tables to be ignored, quickly grokking the table being dumped can be annoying with the current implementation as you have to view/modify the very beginning of one line with the very end of one line.
=> Refactor mysqldump command order

src/N98/Magento/Command/System/Cron/AbstractCronCommand.php
Running cron related commands such us:
```
$ n98-magerun.phar sys:cron:list
```
or
```
$ n98-magerun.phar sys:cron:run
```
throws a PHP fatal error:
> PHP Fatal error:  Unsupported operand types in phar:///usr/local/bin/n98-magerun.phar/src/N98/Magento/Command/System/Cron/AbstractCronCommand.php on line 35
PHP Stack trace:
PHP   1. {main}() /usr/local/bin/n98-magerun.phar:0
PHP   2. N98\Magento\Application->run() /usr/local/bin/n98-magerun.phar:8
PHP   3. Symfony\Component\Console\Application->run() phar:///usr/local/bin/n98-magerun.phar/src/N98/Magento/Application.php:656
PHP   4. N98\Magento\Application->doRun() phar:///usr/local/bin/n98-magerun.phar/vendor/symfony/console/Application.php:126
PHP   5. Symfony\Component\Console\Application->doRun() …
=> Fix unsupported operand types error in cron commands

src/N98/Magento/Command/System/Setup/CompareVersionsCommand.php
The current mechanism forces all the errored setup resources to the bottom of the table.
```
magerun sys:setup:compare-versions
```
```
+-----------------------+----------------+----------------+----------------+--------+
| Setup                 | Module         | DB             | Data           | Status |
+-----------------------+----------------+----------------+----------------+--------+
| admin_setup           | 1.6.1.2        | 1.6.1.2        | 1.6.1.2        | OK     |
| bronto_common_setup   | 2.4.4          | 2.4.2.2        | 2.4.2.2        | Error  |
+-----------------------+----------------+----------------+----------------+--------+
```
The proposed update is to add an `--errors-only` option, that will filter out all the rows with Status = "OK".
```
magerun …
```
=> Add errors-only filter to sys:setup:compare-version

src/N98/Magento/Command/Admin/User/LockdownCommand.php, src/N98/Magento/Command/Admin/User/UnlockCommand.php, tests/N98/Magento/Command/Admin/User/UnlockUserCommandTest.php
Fixes pull request #762 
- Merge conflicts resolved with #810 changes
- Compatibility changes made between LockdownCommand and UnlockCommand for consistency
- Messages adjusted slightly in UnlockCommand messages from original command
=> Adding a prompt when unlocking all admin users.

readme.rst, src/N98/Magento/Command/Config/AbstractConfigCommand.php, src/N98/Magento/Command/Config/DeleteCommand.php, src/N98/Magento/Command/Config/SetCommand.php
Subject: Add config:delete --force option
Fixes #811 #814.
As discussed in #811 and #814 the recent changes in 77df9c2b7110b370cfb6608aed333e0777951622 prevent some users who have set non-standard `scope-id` and `scope` combinations from using `config:delete`.
Additionally if these _non-standard_ `scope-id` and `scope` combos are used `--all` isn't true to it's documentation. 
This PR adds a `--force` option to `config:delete` to avoid this lock-out. This option does two things:
1. When used without the `--all` option: the _"positive integer"_ validation of `scope-id` is skipped, allowing usage of `0` `scope-id` for both `websites` and `stores` scopes.
2. When used with the `--all` option: `true` is passed to [`Mage::app()->getStores()`](https://github.com/OpenMage/magento-mirror/blob/mage …
=> Add config:delete --force option

config.yaml
as for versions < 1.8.0.0 only zips are available through the download API we might switch generally to zips (otherwise checksum verification will fail in 3rd party implementations or we have to deal with superfluous conditionals)
also add the official sources for 1.9.2.0 - 1.9.2.3 (these still need the magedownload-cli approach)
=> add official version of magento-ce-1.9.2.0 - magento-ce-1.9.2.3 / switch to zip format

src/N98/Magento/Command/Developer/Module/ListCommand.php
Fixes a rare PHP notice in the `dev:module:list` command.
One of the modules in our shops has this module xml file:
```xml
<config>
<modules>
<Mage_Ogone>
<active>false</active>
</Mage_Ogone>
<Netresearch_OPS>
<active>true</active>
<codePool>community</codePool>
<depends>
<Mage_Sales/>
<Mage_Payment/>
</depends>
</Netresearch_OPS>
</modules>
</config>
```
The `Mage_Ogone` module referenced here was initially included in older Magento versions (like CE 1.4 and CE 1.5 if I remember correctly).
The `Netresearch_OPS` module integrates with the same Payment Provider, and they decided to disable the default module which came with Magento.
In newer versions of Magento, the `Mage_Ogone` is no longer is included.
So, on a newer Magento version, if you run the `dev:module:list` command, it will …
=> Fixes a rare PHP notice in the dev:module:list command.

config.yaml, readme.rst, src/N98/Magento/Command/Developer/EmailTemplate/UsageCommand.php
Adds command to list transactional email template usage.
When an installation has many transactional emails, it is easy
to lose track of which ones are currently being used. As you can
also fall back to using templates in the source code, it is helpful
to be able to see which email templates are in use and which can be deleted.
This command allows you to see which email templates are used, and in
which scopes of the configuration that is.
I've not added unit tests, let me know if these are required and I'll get them written.
=> Adds command to list transactional email template usage.

config.yaml
Subject: Add two tables to be stripped when using the @customers directive 
Fixes: 
Fatal error (FK constraint violations) when using the Enterprise backup functionality on a database which was dumped by N98 with customer data stripping. The salesrule_coupon_usage and salesrule_customer tables both reference customer_entity.
=> Additional tables in customer data strip

config.yaml
Fixes #836 
- Add `@emails` db:dump group
- Add it to `@development`
* Resolves #836
=> FIX strip email queue tables for development db:dump commands

src/N98/Magento/Command/System/Cron/AbstractCronCommand.php
- Adds `Model` column to `sys:cron:list` command, showing the model::method that the job uses.
e.g.
changes to
=> Adding model::method to cron list command

readme.rst, src/N98/Magento/Command/Eav/Attribute/Create/DummyCommand.php, tests/N98/Magento/Command/Eav/Attribute/Create/DummyCommandTest.php
Hi guys,
here I am with a new PR from my addons.
Hope my tests are good and the code quality is better than before.
- add a command **eav:attribute:create-dummy-values** to create dummy values for dropdown attributes
- used Faker library to create dummy values
=> Add command eav:attribute:create-dummy-values (with tests)

readme.rst, src/N98/Magento/Command/Eav/Attribute/Create/DummyCommand.php, src/N98/Magento/Command/Eav/Attribute/Create/DummyValues.php, tests/N98/Magento/Command/Eav/Attribute/Create/DummyCommandTest.php
Hi guys,
this version of the command need to be tested on magento version < 1.6.2.0.
Your system has a beautiful test environment with travis ci, so I create this PR to test all the version supported by n98-magerun.
- add a command to create attribute values (only for dropdown attribute)
=> Add command eav:attribute:create-dummy-values

readme.rst, src/N98/Magento/Command/Cache/CleanCommand.php, src/N98/Magento/Command/Cache/FlushCommand.php
Subject: Add option to reinitialise cache when cleaning or flushing
Previously the config cache would always be reinitialised when cleaning
or flushing. This was done to resolve a corner case issue with the
changing of database credentials. As the majority of the time no
reinitialisation is required, we move it into a --reinit option, making
cache cleaning much faster, and less prone to error.
It should be noted that the method used for reinitialisation of the
config cache will reliably corrupt the config cache when using redis.
There is a "reinit" method in the Mage_Core_Model_Config class which
will reinitialise the config cache and not cause any corruption.However,
instead of changing the method used to rebuild the config cache, this
patch simply puts …
=> Add option to reinitialise cache when cleaning or flushing

src/N98/Magento/Command/System/Cron/RunCommand.php
I was running a cron via the CLI yesterday and didn't realise it was throwing an exception. This change makes it so that exceptions are output to the command line.
Output Before:
```
Run Namespace_Module_Model_Cron::run
done
```
Output After:
```
Run Namespace_Module_Model_Cron::run
[Mage_Core_Exception]                          
Exception Message Here
sys:cron:run [job]
```
Running the command with `-v` will also print out the stack trace.
=> Print out cron exceptions

src/N98/Magento/Command/System/Cron/RunCommand.php
Subject: Created_at did not get set in `sys:cron:run`
- Set `created_at` in `cron_schedule` table when running a cron job. Otherwise the `created_at` field gtes set to `'0000-00-00 00:00:00'` in MySQL.
=> Set created_at in schedule when running a cron job

config.yaml
New `eav:attribute:create-dummy-values` and `category:create:dummy` not show in command list because config,yaml was not update or override on master branch
=> [fix] config.yaml - new command not added or override by previous commit

config.yaml, readme.rst, src/N98/Magento/Command/AbstractMagentoCommand.php, src/N98/Magento/Command/Indexer/AbstractMviewIndexerCommand.php, src/N98/Magento/Command/Indexer/ListMviewCommand.php, src/N98/Magento/Command/Indexer/ReindexMviewCommand.php
I've spent too long in my time as a Magento developer teaching the members on my team that the full flat indexer, and the changlog (mview) reindexer do vastly different things under the hood. It's fine to have your product reappear on the frontend when running a full reindex, but when you have to debug and fix something in the changelog process you need a finer level of granularity. Having to debug these on local, production, and every environment in between has left me wanting a standard command to handle this.
I've added two.
1. Show a list of the mview metadata, including how many entries are pending a reindex (can be useful if an indexer gets stuck)
```bash
$ magerun index:list:mview
+---------------------------------+------------------------------------+------------------------------- …
```
=> Add enterprise mview reindex commands

config.yaml
Fix: InstallCommandPackageVersionTest.versionListing
(cherry picked from commit 35cf964)
=> Remove Duplicate entry in config.yaml for magento-mirror-1.9.3.2

src/N98/Magento/Command/ScriptCommand.php
On a failed exectution with --stop-on-error specified, the script
command now throws a non zero exit code.
Fixes #908 exit code should be non-zero if script command fails
=> Updates script command to have non-zero exit code

readme.rst, src/N98/Magento/Application.php
I added this flag while I was trying to debug #938, and although it didn't really help I thought I'd see what you think. 
This is instantiated in much the same way as it is when done via [`index.php`](https://github.com/OpenMage/magento-mirror/blob/magento-1.9/index.php#L70)
I think it may be useful when I plug `magerun sys:setup:run --developer-mode` into a `.travis.yml`, this way I can catch notices/warnings within dodgy setup scripts a lot easier.
~~I just noticed that the `.idea` directory wasn't ignored, feel free to ask me to remove or cherrypick to ignore it if you don't think it's appropriate.~~
=> Magento developer mode

src/N98/Util/Console/Helper/MagentoHelper.php
See 
- https://github.com/netz98/n98-magerun/issues/938
- https://github.com/netz98/n98-magerun/issues/902
Add an additional fallback check for the enterprise layout directory
In 902 I said 
>For visibility there is no app/code/core/Enterprise folder as Enterprise lives under the /vendor directory for this project.
There is still an Enterprise frontend directory as there is no amount of autoloading shenanigans you can do to get them to work in a modern way.
The proposed change will
- Fix enterprise detection for my use case (#902)
- Fix the broken symfony/console errors people are seeing without having to require a change in workflow (#938)
=> Add another fallback check to enterprise detection

config.yaml, readme.rst, src/N98/Magento/Command/Cms/Block/ListCommand.php
Add `cms:block:list` command which outputs like
```bash
/opt/boxen/phpenv/versions/5.5.38/bin/php /Users/lukerodgers/src/magerundemo/bin/n98-magerun --root-dir=/Users/lukerodgers/src/magento-mirror cms:block:list
+----------+---------------------------------+---------------------------+-----------+-----------+
| block_id | identifier                      | title                     | is_active | store_ids |
+----------+---------------------------------+---------------------------+-----------+-----------+
| 1        | footer_links                    | Footer Links              | active    | 0         |
| 2        | footer_links_company            | Footer Links Company      | active    | 0         |
| 3        | cookie_restriction_notice_block | Cookie restriction notice | active    | 0 …
```
=> Add cms:block:list command

src/N98/Magento/Command/Config/AbstractConfigCommand.php, src/N98/Magento/Command/Config/GetCommand.php, src/N98/Magento/Command/Config/SetCommand.php, tests/N98/Magento/Command/Config/GetCommandTest.php
- [x ] Pull request against develop branch (if not, just close and create a new one against it)
- [ x] README.md reflects changes (if any)
Subject: typo in 'config:get' when null value is returned  
Fixes # .
- Typo in response message and class constants
=> Fixed typo in 'config:get' results when returning a 'null' value

src/N98/Magento/Command/System/Cron/RunCommand.php
Hello,
I use `sys:cron:run` occasionally to force a couple of cronjobs to execute outside of their window of execution and also to be able to break execution. Recently I noticed that the command was always being scheduled.
This patches fixes an issue introduced in #966 with the `--schedule` command switch. The `hasOption` method is always returning `true` which causes commands to always be scheduled instead of running immediately as default. The `executeConfigModel` and `scheduleConfigModel` was also
changed in order to avoid using `hasOption` and `!getOption` in the condition which would make it a bit harder to understand.
Also, having `hasOption && getOption` together keeps it consistent with how other commands operate (e.g. [cache:view](https://github.com/netz98/n98-magerun/blob/880b7a6 …
=> Fix immediate execution of sys:cron:run

.travis.yml
Subject: 
Remove the now obsolete global DB env variable as per https://github.com/netz98/n98-magerun/pull/986#issuecomment-388976881
- remove obsolete global `DB` env var for Travis CI
=> chore: remove obsolete global DB env variable

config.yaml
Subject: Don't strip newsletter templates when stripping subscribers
Currently the tool strips the newsletter templates as well as the actual subscriber data (contrary to the description of the `@newsletter` and `@development` group descriptions). This avoids that.
=> Don't strip newsletter templates when stripping subscribers

config.yaml
Was missing since https://github.com/OpenMage/magento-mirror/pull/69 wasn't merged yet. #999 was merged a little too soon, but this should fix the missing shasum.
Fixes #998 .
- Add missing shasum for 1.9.3.10
=> Add shasum for 1.9.3.10

config.yaml
As one of the most active Magento1 Forks, we would appreciate it to also get listed as part of the installable versions.
=> add openmage-lts to installable versions

config.yaml
To be clear on the proposed change: the n98-magerun would scan /usr/share/n98-magerun/modules first, then /usr/local/share/n98-magerun/modules. That would sort of match other system conventions (when you have overrides in /usr/local and packages in /usr).
=> Extra directory for plugins, see #1016

src/N98/Magento/Command/Developer/Ide/PhpStorm/MetaCommand.php
Phpstorm can't resolve methods if helpers are called via helper method:
```
protected function helper($name)
{
return Mage::helper($name);
}
```
```
$this->helper('payment')->getBillingAgreementMethods()
```
This PR takes the already collected helper classes and outputs them in a new file to make them "readable" ...
```
namespace PHPSTORM_META {
override( \Mage_Admin_Model_User::_getHelper(0),
map( [
'adminnotification/data' => \Mage_AdminNotification_Helper_Data::class,
...
```
Note: does not support old output format.
**Update:**
Detect created blocks
```
$select = $this->getLayout()->createBlock('core/html_select')
````
=> Phpstorm meta files - support dynamically called helpers + createBlock() methods

src/N98/Magento/Command/Database/DumpCommand.php, src/N98/Util/Exec.php, src/N98/Util/OperatingSystem.php
Pipe commands are not handled correct.
The db:dump command will always return "0" which means "correct" even if an error occurs.
=> fix db dump error status

src/N98/Magento/Command/ScriptCommand.php
=> Remove not needed "continue" to be compatible with PHP 7.3

src/N98/Magento/Command/Cache/AbstractCacheCommand.php
Applies the change suggested in the comments of issue https://github.com/netz98/n98-magerun/issues/583
Subject:
Fixes #583 
- Changes the config init logic to Magento's own reinit function in the Config model to prevent issues with the `CONFIG` cache tag being cleared without being rebuilt when using the Redis cache storage engine.
=> Change config init to Magento's reinit function

composer.json, composer.lock
Compsoer 2.0 will not allow package names with uppercase letters.
Fixes: Invalid composer.json
=> Fix invalid composer package name

src/N98/Magento/Command/Indexer/AbstractMviewIndexerCommand.php, src/N98/Magento/Command/Indexer/ListMviewCommand.php
```
PHP Fatal error:  Uncaught ArgumentCountError: Too few arguments to function N98\Magento\Command\AbstractMagentoCommand::_getModel()
```
When I built these commands in https://github.com/netz98/n98-magerun/pull/891 I erroneously neglected to pass the 2nd argument to `_getModel` and `_getSingleton`
I was using this today on a client running PHP 7 and this is now a proper error, previously I imagine a warning or notice slipped by on PHP 5.
=> Fix instances of PHP Fatal error:  Uncaught ArgumentCountError

src/N98/Magento/Command/Cache/CleanCommand.php, src/N98/Magento/Command/Cache/FlushCommand.php
DB init is triggered by Mage::app().
We catch the exception of the wrong cached db credentials an continue.
Fixes #1046
- Catch exception do not stop command execution if wrong DB credentials are stored.
=> Possible fix for #1046

config.yaml
Avoid new Magento policy fail
- Password must include both numeric and alphabetic characters.
- Password must be at least of 14 characters.
=> Increase default password length to comply password policy

config.yaml
Add Magento 1.9.4.2 - 1.9.4.5 from OpenMage/magento-mirror
- Add new Magento Versions from OpenMage
=> Add Magento 1.9.4.2 - 1.9.4.5

config.yaml
- Remove `mcrypt` from list of required PHP extensions.
=> Remove mcrypt from required PHP extensions

src/N98/Magento/Command/Database/DumpCommand.php
Issues #1127:
backport --no-tablespaces option from n98-magerun2
=> add "no-tablespaces" option

src/N98/Magento/Command/Developer/Ide/PhpStorm/MetaCommand.php, tests/N98/Magento/Command/Developer/Ide/PhpStorm/MetaCommandTest.php
Update for new standard phpstorm.meta used by the JetBrains/phpstorm-stubs library:
https://github.com/JetBrains/phpstorm-stubs
I replaced the "$STATIC_METHOD_TYPES[]" wrapper with the "override()" method.
https://github.com/netz98/n98-magerun/issues/1140
=> Update for new standard phpstorm.meta used by the JetBrains/phpstorm-stubs library

.github/workflows/ci.yml, build/local/test_setup.sh
After starting the migration from Travis-CI to Github CI in 3ca8553 the
build scripts in general came to attention for review.
Most prominently likely is
build/local/test_setup.sh
which is the standard setup test/build: Install a Magento version with
Magerun.
Despite being important in (local!) CI, it has not yet been put into the
projects CI so far (at least not in the form of the build script).
Add the Test Setup to the CI running w/ Github Actions.
This change-set contains required changes to the build script itself so
that the db password and the Magento version can be injected. Change here
is to allow any of the test_setup_* parameters to be overridden which
previously was not possible.
Rationale on these changes:
The Ubuntu-18.04 runner on Github Actions currently runs PHP 8.0:
- As …
=> Run Test Setup in Github CI

.github/workflows/ci.yml
Missing the "master" build on Github Actions.
The macro is for a workflow template only.
Fix is to use verbatim "master" again.
Related-Issue: #1138
---
=> Fix "$default-branch" macro use

composer.json, composer.lock, tests/N98/Magento/ApplicationTest.php, tests/N98/Magento/TestApplication.php
Previously while unsharing the shared folder in #1149 it came to attention 
that the autoloading in projects composer.json was still configured as
PSR-0 which is deprecated since longer.
Change is to switch to PSR-4 autoloading.
---
=> Change autoloading from PSR-0 to PSR-4

config.yaml
Use 95MB compressed sample data instead of current 430MB.
I'v just compressed mp3 to 48k and reduced image quality to 50%.  It's not as optimized as https://github.com/Vinai/compressed-magento-sample-data yet, but that's coming. (Eventually.)
---
I tried `tar.xz` (~50MB) but install sample data fails with ...
```
[UnexpectedValueException]                                                                                                                                    
internal corruption of phar "/home/sr/workspace/tests/n98/magento/_temp_demo_data/3b521eeeb430578bc0efd3d2876d834a.xz" (__HALT_COMPILER(); not found)  
```
=> Use compressed sample-data

.github/workflows/ci.yml, .travis.yml, CHANGELOG.md, config.yaml
- Add OpenMage 20.0.10 as new version to installer.
- Set OpenMage 20.0.10 as version in test setup
=> Add OpenMage 20.0.10

.github/dependabot.yml
This should help with keeping the GitHub actions updated on new releases. This will also help with keeping it secure.
Dependabot helps in keeping the supply chain secure https://docs.github.com/en/code-security/dependabot
GitHub actions up to date https://docs.github.com/en/code-security/dependabot/working-with-dependabot/keeping-your-actions-up-to-date-with-dependabot
https://github.com/ossf/scorecard/blob/main/docs/checks.md#dependency-update-tool
Signed-off-by: neilnaveen <42328488+neilnaveen@users.noreply.github.com>
=> chore: Dependabot check Github Actions daily
