netz98/n98-magerun

src/N98/Magento/Command/ConfigurationLoader.php

- Handle filesystem based config loading problems
- Give error messages that show the filename in question
- Minor WS fix

[BUGFIX] #466 Configuration loader fatal error

---

config.yaml
readme.rst
src/N98/Magento/Command/Admin/User/ToggleActiveCommand.php

Activate/deactivate user admins.

[FEATURE] new command admin:user:toggle-active

---

src/N98/Magento/Command/Installer/InstallCommand.php

Add db_prefix support to installer command.

---

.travis.yml

switching from mysql-sockets (localhost) to network (127.0.0.1)
replace travis mysql5.6 with mysql5.5
fixes #536

fixing travis build environment

---

src/N98/Magento/Command/Database/Compressor/Uncompressed.php
src/N98/Magento/Command/Database/DumpCommand.php

added option to dump the database in xml format

---

src/N98/Magento/Command/Database/DumpCommand.php

Add --hex-blob flag to dump options.

Add option to dump binary columns using hexadecimal notation

---

src/N98/Magento/Command/AbstractMagentoCommand.php
src/N98/Magento/Command/Developer/Module/Observer/ListCommand.php
src/N98/Magento/Command/MagentoConnect/AbstractConnectCommand.php

after the recent 7d40222 update based on scrutinizer results and own
comments (reduce visibility, extract).

reduced complexity observer list command

---

autocompletion/oh-my-zsh/n98-magerun.plugin.zsh
readme.rst

Opening new pull request to develop, as per https://github.com/netz98/n98-magerun/pull/592
Proposed zsh completion fix for #589

Fixing ZSH Completetion on OSX

---

autocompletion/bash/bash_complete
readme.rst

Proposed bash completion fix for #589

Bugfix/Bash Completion on OS X

---

readme.rst

Update lookup command

---

autocompletion/zsh/n98-magerun.plugin.zsh

Proposed ZSH auto completion independent of configuration noted in #589

Bugfix/Configuration Agnostic ZSH Completion

---

src/N98/Magento/Command/System/Check/ResultCollection.php
src/N98/Magento/Command/System/Check/SimpleCheck.php
src/N98/Magento/Command/System/Check/StoreCheck.php
src/N98/Magento/Command/System/Check/WebsiteCheck.php
src/N98/Magento/Command/System/CheckCommand.php

- Warning is given if checks that are to be executed aren't (e.g. a
website check has been configured but there is no website).
- If a check command is unknown to execute, an exception is given.
- Added docblocks

Improvements on Checks

---

src/N98/Magento/Command/System/Check/Result.php
src/N98/Magento/Command/System/Check/Settings/BaseUrlCheckAbstract.php
src/N98/Magento/Command/System/Check/Settings/CheckAbstract.php
src/N98/Magento/Command/System/Check/Settings/CookieDomainCheckAbstract.php
src/N98/Magento/Command/System/Check/Settings/SecureBaseUrlCheck.php
src/N98/Magento/Command/System/Check/Settings/UnsecureBaseUrlCheck.php

- Checks show the configuration values so it's more transparent to review a check (cookie-domain and base-url).
- Duplicate code has been reduced for base-url checks.

Further improvements on checks

---

.travis.yml
config.yaml

Closes #609
$ ls --full-time -Gg 1.9.2.0.tar.gz
-rw-r--r-- 1 24256895 2015-07-21 13:27:10.283278676 +0200 1.9.2.0.tar.gz
$ shasum 1.9.2.0.tar.gz
da66104d800e815ec996fef31170671fbb8a7bca  1.9.2.0.tar.gz

Package magento-mirror-1.9.2.0

---

tests/N98/Magento/Command/Cache/ViewCommandTest.php

CommandTester normalization of Display

Interop diverse

---

autocompletion/fish/n98-magerun.phar.fish

I started to play with the [fish shell](http://fishshell.com/) and I thought it would be cool if there was n98-magerun autocompletion for it, too.

Added Fish Autocompletion File

---

changes.txt
src/N98/Magento/Command/Developer/Module/Rewrite/AbstractRewriteCommand.php
src/N98/Magento/Command/LocalConfig/GenerateCommand.php
src/N98/Magento/Command/MagentoConnect/AbstractConnectCommand.php
src/N98/Util/Console/Helper/MagentoHelper.php

all-time low for scrutinizer patches hopefully

move on + cs fixes

---

src/N98/Magento/Command/Database/QueryCommand.php
src/N98/Magento/Command/Developer/Ide/PhpStorm/MetaCommand.php
src/N98/Magento/Command/Installer/InstallCommand.php
tests/N98/Magento/Command/Config/GetCommandTest.php
tests/N98/Magento/Command/Database/DumpCommandTest.php
tests/N98/Magento/Command/Developer/Ide/PhpStorm/MetaCommandTest.php
tests/N98/Magento/Command/Developer/Theme/DuplicatesCommandTest.php
tests/N98/Magento/Command/Installer/InstallCommandTest.php
tests/N98/Magento/Command/Script/Repository/RunCommandTest.php

a bag of interoperability changes and some more CS fixes.

move-on with interop fixes

---

changes.txt
config.yaml

[FIX] Fix Magento 1.9.2.1 announced as 1.9.2.0

---

src/N98/Magento/Command/System/Check/MySQL/VersionCheck.php

[FIX] fix fatal error in VersionCheck

---

src/N98/Magento/Command/AbstractMagentoCommand.php

Removed unneeded duplicate assignment.

Removed duplicate assignment

---

.travis.yml
changes.txt
src/N98/Magento/Application.php
src/N98/Magento/Command/Cache/DisableCommand.php
src/N98/Magento/Command/Cache/EnableCommand.php
src/N98/Magento/Command/ConfigurationLoader.php
src/N98/Magento/Command/Developer/ConsoleCommand.php
src/N98/Magento/Command/Indexer/ReindexCommand.php
src/N98/Magento/Command/Installer/InstallCommand.php
src/N98/Magento/Command/ScriptCommand.php
src/N98/Util/BinaryString.php
tests/N98/Util/StringTest.php

- add a lint task with php 7 in travis build
- rename String to BinaryString
- remove unused
Fixes #691

[FIX] #691 PHP 7 forward compat

---

src/N98/Magento/Command/Developer/TemplateHintsBlocksCommand.php
src/N98/Magento/Command/Developer/TemplateHintsCommand.php

Resolves #736, adding admin store view to template hints toggles

---

src/N98/Magento/Command/PHPUnit/TestCase.php

Read the guidelines carefully :)
* changed hardcoded location to defined PHPUNIT_COMPOSER_INSTALL

Changed hardcoded autoload.php to dynamic

---

src/N98/Magento/Command/System/Cron/AbstractCronCommand.php

cron expression parsing now filters out the (optional) year element (6th
element) as it is not displayed in the output table and did cause an error
condition if set.

[TASK] #785 fix cron expression parsing

---

src/N98/Magento/Application/ConfigurationLoader.php

Fixes bug which was introduced in latest magerun version. 
See #799 for more information.

Fix magerun plugin loader

---

changes.txt
src/N98/Magento/Command/Config/AbstractConfigCommand.php
src/N98/Magento/Command/Config/DeleteCommand.php
src/N98/Magento/Command/Config/GetCommand.php
src/N98/Magento/Command/Config/SetCommand.php

Fixes an issue that config:delete did not delete.

Fix config:delete

---

config.yaml
readme.rst
src/N98/Magento/Command/Admin/User/LockCommand.php
src/N98/Magento/Command/Admin/User/LockdownCommand.php
src/N98/Magento/Command/Admin/User/UnlockCommand.php
tests/N98/Magento/Command/Admin/User/LockCommandTest.php

Implements #808 
* Add `lock` command
* Add number of admins unlocked to output message for `unlock` command
* Add `lockdown` command

[#808] Added admin:user:lock and lockdown commands

---

readme.rst

- [v ] Pull request against develop branch (if not, just close and create a new one against it)
- [ v] README.md reflects changes (if any)
Fixes # .
- Add Homebrew installation

Add Homebrew installation

---

readme.rst

- Documentation update, add proper command prior to search "text" argument.

Update example to use config:search command

---

readme.rst
res/twig/dev/module/create/app/etc/modules/config.twig
src/N98/Magento/Command/Developer/Module/CreateCommand.php
tests/N98/Magento/Command/Developer/Module/CreateCommandTest.php

Subject: Added support for creating controllers folder with dev:module:create command
Also https://github.com/netz98/n98-magerun/wiki/Twig should be updated when PR gets merged

Added support for creating controllers folder

---

readme.rst
src/N98/Magento/Command/Category/Create/DummyCommand.php
tests/N98/Magento/Command/Category/Create/DummyCommandTest.php

Fixes # .
This is the new PR with unit test. Same functionality as #844 
Hope it has a good code quality and merge in your future version.
Thank you!

Add command category:create:dummy (with tests)

---

src/N98/Magento/Command/Category/Create/DummyCommand.php
src/N98/Magento/Command/Eav/Attribute/Create/DummyCommand.php

- improve code standard and quality for PR merged #849 and #845
- reformat text
- no feature of fix added with this pull request, is a little PR to close last discussion on #849

Improve code quality and reformat text

---

readme.rst

Add curl method in README, such as magerun2.

Optional Curl

---

autocompletion/bash/bash_complete
readme.rst
src/N98/Magento/Command/Database/ConsoleCommand.php

Subject: Adding option to avoid hashing delay
Fixes #878 
- db:console now offers --no-auto-rehash option to speed up the mysql client (as if adding the -A or --no-auto-rehash option to mysql)

Noautorehash option

---

readme.rst

Unless I'm missing something, the website doesn't provide an md5sum
https://files.magerun.net/

Fix file integrity checking guide

---

CHANGELOG.md
config.yaml

[UPDATE] add magento 1.9.3.3 fixes #920

---

.travis.yml
config.yaml

Fixes # .
add magento 1.9.3.4
- ...
- ...
- ...

add magento 1.9.3.4

---

readme.rst

Per issue #935
Fixes # .
- ...
- ...
- ...

Update readme.rst with link to check checksum

---

.travis.yml
build/travis/before_script.sh

Fixes problems with travis server.

Remove PHP 5.3 after travis ended support

---

.travis.yml
CHANGELOG.md
config.yaml
src/N98/Magento/Command/Installer/InstallCommand.php

Add Magento CE 1.9.3.6

---

readme.rst
src/N98/Magento/Command/System/Cron/RunCommand.php

Add option to schedule cron in magento crontab instead of running. This avoid running with right problems, and follow all magento native workflow.
More clean in most cases.

Add option to schedule cron in magento crontab instead of running

---

.travis.yml
CHANGELOG.md
config.yaml
src/N98/Magento/Command/Installer/InstallCommand.php

Fixes #967.
- Add Magento 1.9.3.7

#967 Adds Magento 1.9.3.7

---

src/N98/Magento/Command/Developer/Module/Disableenable/AbstractCommand.php

Mage allows multiple modules to be declared in the same file in
app/etc/modules, however the old code didn't support this. Search
for the last included file that includes the declartion for the
passed module name.
Fixes # .
- ...
- ...
- ...

Add support for multi module declaration files.

---

src/N98/Magento/Command/Database/ImportCommand.php

Subject: add --stdin option to db:import
Fixes #934 .

Add ability to import db from STDIN

---

.travis.yml
config.yaml
src/N98/Magento/Command/Installer/InstallCommand.php

Fixes #978 .
- Adds Magento 1.9.3.8

Adds Magento 1.9.3.8

---

.travis.yml

- add the missing database setting to the build matrix

chore: add database setting to matrix

---

.travis.yml
config.yaml
src/N98/Magento/Command/Installer/InstallCommand.php

Fixes #996 .
- Adds Magento 1.9.3.9

Adds Magento 1.9.3.9

---

.travis.yml
config.yaml

Add PHP 7.2 tests to travis test matrix

Add php72 support to travis test matrix

---

readme.rst

Subject: Fix formatting in readme

Fix formatting in readme

---

src/N98/Magento/Command/Database/AbstractDatabaseCommand.php
src/N98/Magento/Command/Database/DumpCommand.php
src/N98/Magento/DbSettings.php
src/N98/Util/Console/Helper/DatabaseHelper.php

Fixes #1018
- To add `--connection` option for the `db:dump` command

Add connection option for db:dump command

---

readme.rst

Add script to command example.
- Documentation update

Update readme.rst - script command example fix

---

src/N98/Magento/Command/Customer/CreateCommand.php

Hide customer password in interactive mode

---

config.yaml

- Add Magento 1.9.4.1 into the `n98-magerun install` command

Adding Magento 1.9.4.1

---

config.yaml

Add latest version to installer.

Adding OpenMage Magento LTS 1.9.4.x

---

src/N98/Magento/Command/Developer/Ide/PhpStorm/MetaCommand.php

Ref #1029 .... just for some models :) Should cover all occurrences now :)

IDE Meta: add support for some more classes

---

config.yaml
tests/N98/Magento/Command/Installer/InstallCommandPackageVersionTest.php

Fix for PR #1036

---

src/N98/Util/Console/Helper/ParameterHelper.php

Fixes #1021
+ BUG: did not provide list to chose websites from when creating customer
+ Since: a01062eb739c7fcfafe67728d47967c5b4a80daf
- Properly return list of websites to display on CLI for dev to choose from
- Changes does not implement anything new, only provides fixes for current functionality.

FIX: \N98\Util\Console\Helper\ParameterHelper::websitesQuestion

---

config.yaml
tests/N98/Magento/Command/Installer/InstallCommandPackageVersionTest.php

Fixes https://github.com/netz98/n98-magerun/pull/1034#issuecomment-643739294
- removed outdated OpenMage LTS 1.9.3.x branch
https://github.com/OpenMage/magento-lts/blob/1.9.4.x/SECURITY.md

Removed OpenMage LTS 1.9.3.x

---

.github/ISSUE_TEMPLATE/01_bugs.md
.github/ISSUE_TEMPLATE/02_feature_request.md
.github/ISSUE_TEMPLATE/03_enhancement.md
.github/ISSUE_TEMPLATE/04_questions.md
.github/ISSUE_TEMPLATE/05_support.md
.github/ISSUE_TEMPLATE/06_other.md
.github/ISSUE_TEMPLATE/config.yml

Subject: Add templates for new Github issues

Add Github issue templates

---

src/N98/Magento/Command/Database/AbstractShowCommand.php
tests/N98/Magento/Command/Database/VariablesCommandTest.php

Subject: Backport db:status command fixes

Backport db:status fixes of n98-magerun2

---

src/N98/Magento/Command/System/InfoCommand.php

Show correct OpenMage version.

Show correct OpenMage version

---

src/N98/Magento/Command/Config/DeleteCommand.php

fixes typo in help

---

src/N98/Magento/Command/System/Cron/RunCommand.php

Solves issue #1115
[X] Pull request against develop branch (if not, just close and create a new one against it)
Subject: Fix issue with AOE scheduled module
Fixes #1115 
Set scheduled_at for adhoc cronjob execution. This fixes an issue with Aeo Schuler which observes the beforeSave event and reuses the timestamp which was null before.

Add scheduled_at to fix issue with Aoe_Scheduler

---

.travis.yml
config.yaml
tests/N98/Magento/Command/Developer/Ide/PhpStorm/MetaCommandTest.php
tests/N98/Magento/Command/Developer/Module/Dependencies/FromCommandTest.php
tests/N98/Magento/Command/System/InfoCommandTest.php

Subject: Add OpenMage LTS 20.0.3

Add OpenMage LTS 20.0.3

---

.github/workflows/ci.yml

Fix-up of a0c9d46cf29628f8edf59174952870020372b4ef

Fix clover.xml path

---

.github/workflows/ci.yml
composer.lock

From today; CI discovered an issue.

Dependabot bumps

---

.github/workflows/ci.yml
composer.lock

Subject: Update PHPUnit Dependencies
Fixes issue with myclabs/deep-copy package

Update Composer dependencies to fix error with myclabs/deep-copy

---

.github/workflows/ci.yml
.travis.yml
config.yaml

Subject: OpenMage v20.0.14
- Add openmage v20.0.14 to Travis
- Add openmage v20.0.14 to config.yaml for installer command

Add OpenMage v20.0.14
